from selenium import webdriver
import time

browser = webdriver.Chrome()

#GLOBAL VARIABLES
page = 'https://www.memecenter.com/fun/3377699729004618/egyptian-pharoah-proud-noises/comments/12362319'
upvoteCSS = '#comments > div:nth-child(12) > div.sub-comment > div > div.sub-comment > div > div.sub-comment > div > div.sub-comment > div > div.sub-comment > div > div > table > tbody > tr > td:nth-child(2) > div.comment-buttons > div.downvote.act_comvote'
loginNotifCSS = '#fdc_ntfnotf > div.notification-icon.act_dropdownact'
usernameFieldCSS = '#l_username'
passwordFieldCSS = '#l_password'
loginCSS = '#login_form > div > div.npc-bottom > input'
password = 'asdasd'
logout = 'https://www.memecenter.com/auth/logout'

#script start
browser.get(page)
browser.maximize_window()

#accounts
loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('xxx8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ccc8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('vvv8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('bbb7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('nnn8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('mmm8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('fff8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg1')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg2')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg3')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg4')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg5')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg6')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg7')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)

loginNotif = browser.find_element_by_css_selector(loginNotifCSS)
loginNotif.click()
usernameField = browser.find_element_by_css_selector(usernameFieldCSS)
usernameField.send_keys('ggg8')
passwordField = browser.find_element_by_css_selector(passwordFieldCSS)
passwordField.send_keys(password)
login = browser.find_element_by_css_selector(loginCSS)
login.click()
upvoteButton = browser.find_element_by_css_selector(upvoteCSS)
upvoteButton.click()
browser.get(logout)
browser.get(page)



